import { TicketPriority, TicketType } from "../../constants";
import { Feature } from "./Feature";
import { Project } from "./Project";
import { Sprint } from "./Sprint";
import { Task } from "./Task";
import { TicketStatus } from "./TicketStatus";
import { User } from "./User";

export type Ticket = {
  id: number;
  title: string;
  description?: string;
  acceptanceCriteria?: string;
  discussion?: string;
  createdBy: string;
  updatedBy?: string;
  createdAt: string;
  updatedAt: string;
  status: TicketStatus;
  statusId: string;
  featureId?: string;
  feature?: Feature;
  projectId?: string;
  project?: Project;
  tasks: Task[];
  sprintId?: string;
  sprint?: Sprint;
  order: number;
  additionalDetails?: string;
  designInformation?: string;
  notes?: string;
  priority: TicketPriority;
  type: TicketType;
  assignedTo?: string;
  assignedUser?: User;
  estimatedHours?: number;
  remainingHours?: number;
  completedHours?: number;
  storyPoints?: number;
  dueDate?: string;
  isBlocked?: boolean;
  blockedBy?: number | null;
  blockingTicket?: Ticket;
  tags?: string[];
  blockedTickets?: Ticket[];
  _count: any;
  pairProgrammingUsers: User[];
};
