-- CreateEnum
CREATE TYPE "TicketType" AS ENUM ('PRODUCT_BACKLOG_ITEM', 'BUG_TICKET', 'TECHNICAL_TICKET', 'SPIKE', 'CHANGE_REQUEST', 'DEPLOYMENT', 'CODE_REVIEW', 'DOCUMENTATION', 'HOTFIX', 'PERFORMANCE_IMPROVEMENT', 'UI_UX_IMPROVEMENT', 'SECURITY_FIX');

-- AlterTable
ALTER TABLE "Ticket" ADD COLUMN     "type" "TicketType" NOT NULL DEFAULT 'PRODUCT_BACKLOG_ITEM';
