export enum Role {
  ADMIN = "ADMIN",
  PROJECT_MANAGER = "PROJECT_MANAGER",
  PRODUCT_OWNER = "PRODUCT_OWNER",
  BUSINESS_ANALYST = "BUSINESS_ANALYST",
  DEVELOPER = "DEVELOPER",
  QUALITY_ASSURANCE = "QUALITY_ASSURANCE",
}
